name: Manifest

on:
  push:
    branches: [ master ]

jobs:
  create-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update root manifest
        run: ls -d */ | sed 's/\///g' > manifest
      - name: Upsert post manifests
        run: ls -d */ | sed 's/\///g' | xargs -n 1 -I {} sh -c "ls {} | grep [0-9][0-9] > {}/manifest"
      - name: Check in
        run: |
          git config --global user.email "bot@dom.is"
          git config --global user.name "Bot (via Github Actions)"
          git add . && git commit -m 'Upsert manifests' && git push origin master
